#!/usr/bin/env node

const commander = require('commander')
const { prompt, Separator } = require('inquirer')
const RevealAddress = require('./index')


commander
    .command('reveal')
    .description('show address and private key from mnemonic words')
    .option('-w, --words <words>', 'Mnemonic words')
    .option('-n, --number <number>', 'Number of address to show')
    .option('-p, --hdPath <hdPath>', 'Derivation Path')
    .option('-t, --type <type>', 'Type of network')
    .action(async (params) => {
        const questions = [
            {
                type: 'password',
                name: 'words',
                message: 'Enter mnemonic words'
            },
            {
                type: 'number',
                name: 'number',
                message: 'Enter number of address to show',
                default: 3
            },
            {
                type: 'list',
                name: 'hdPath',
                message: 'Enter Derivation Path',
                choices: [
                    { name: "TomoChain - m/44'/889'/0'/0", value: "m/44'/889'/0'/0" },
                    { name: "Ethereum - m/44'/60'/0'", value: "m/44'/60'/0'" },
                    { name: "Ledger Live - m/44'/60'/0'/0", value: "m/44'/60'/0'/0" },
                    { name: "Tron network - Ledger Live - m/44'/195'/0'/0", value: "m/44'/195'/0'/0" },
                    { name: "Solana - m/501'/0'/0 - deprecated", value: "0" },
                    { name: "Solana - m/44'/501'/0' - bip44", value: "1" },
                    { name: "Solana - m/44'/501'/0'/0' - bip44Changed", value: "2" }
                ]
            },
            {
                type : 'list',
                name : 'type',
                message : 'Choose type of network',
                default: 'TomoChain - Ethereum',
                choices: ['TomoChain - Ethereum', new Separator(), 'Bitcoin', new Separator(), 'Tron', new Separator(), 'Solana']
            }
        ]
        prompt(questions).then(async answers => {
            try {
                let result
                if (!answers.words) {
                    throw new Error('mnemonic words are required')
                }
                switch (answers.type) {
                case 'TomoChain - Ethereum':
                    result = await RevealAddress.tomo(answers.words.trim(), answers.number, answers.hdPath.trim())
                    break
                case 'Bitcoin':
                    result = await RevealAddress.bitcoin(answers.words.trim(), answers.number, answers.hdPath.trim())
                    break
                case 'Tron':
                    result = await RevealAddress.tron(answers.words.trim(), answers.number, answers.hdPath.trim())
                    break
                case 'Solana':
                    result = await RevealAddress.solana(answers.words.trim(), answers.number, answers.hdPath.trim())
                    break
                default:
                    result = await RevealAddress.tomo(answers.words.trim(), answers.number, answers.hdPath.trim())
                    break;
                }
                console.log(JSON.stringify(result, null, 2))
            } catch (error) {
                throw error
            }
        })
    })

commander.parse(process.argv)
